// generate_statements.js

import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';
import { getAllOps } from 'adacad-drafting-lib';

// In ES Modules, __dirname is not available.
// This is the standard way to replicate it.
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const outputFilePath = path.join(__dirname, 'src/components/import_helper.js');
const oplist = getAllOps();

async function generateModuleStatements() {
    try {


        // Read the filenames from the source directory
        // const files = await fs.readdir(directoryPath);
        let generatedCode = '// This file is auto-generated by the generate_imports script\n\n';

        // Loop through each file and generate an import statement
        for (const op of oplist) {

            if (oplist.draft === undefined) {
                generatedCode += `import  ${op.name}_img  from 'adacad-drafting-lib/markdown/${op.meta.img}';\n`;
                generatedCode += `import  ${op.name}_md  from 'adacad-drafting-lib/markdown/${op.name}.md';\n`;
                generatedCode += `import  {${op.name}}  from 'adacad-drafting-lib/operations/${op.name}/${op.name}.js';\n`;
            }
        }


        generatedCode += `export const assets = [\n`;

        // Loop through each file and generate an import statement
        for (const op of oplist) {
            //const fileExt = path.extname(file);
            // Filter for files with a .js extension to avoid non-JS files

            if (oplist.draft === undefined) {
                generatedCode += `{\nname: '${op.name}',\n img: ${op.name}_img,\n md: ${op.name}_md,\njs: ${op.name}\n},\n`
            }
        }


        generatedCode += `];\n`;


        // Write the generated code to the output file
        await fs.writeFile(outputFilePath, generatedCode, 'utf8');

        console.log(`Successfully generated ES Module statements and wrote to ${outputFilePath}`);
    } catch (err) {
        console.error('An error occurred:', err);
    }
}

async function generateDocumentationPage(op) {
    try {
        const category = (op.meta.categories) ? op.meta.categories[0].name : 'undefined';
        const file_path = path.join(__dirname, `/docs/reference/operations/${category}/${op.name}.md`);

        //write front matter
        let generatedCode = `---\ntitle: ${op.meta.displayname}\n`;
        generatedCode += `sidebar_label: ${op.meta.displayname}\n`;
        generatedCode += `slug: ${op.name}\n`;
        generatedCode += `sidebar_class_name: ${category} opItem\n`;
        generatedCode += `editUrl: 'https://github.com/UnstableDesign/AdaCAD-Library/blob/main/src/operations/${op.name}/${op.name}.ts'\n`;
        generatedCode += `---\n\n`
        generatedCode += `import {OperationHeader} from '@site/src/components/OperationPage';\nimport ImportedMarkdown from 'adacad-drafting-lib/markdown/${op.name}.md';\n\n`;

        generatedCode += `<OperationHeader name='${op.name}' />\n\n`;
        generatedCode += `<ImportedMarkdown />\n\n`;
        generatedCode += `## Developer\n\n`;

        generatedCode += '```ts reference\n'
        generatedCode += `https://github.com/UnstableDesign/AdaCAD-Library/blob/main/src/operations/${op.name}/${op.name}.ts\n`
        generatedCode += '```'

        // Write the generated code to the output file
        await fs.writeFile(file_path, generatedCode, 'utf8');

        console.log(`Successfully generated ES Module statements and wrote to ${file_path} `);
    } catch (err) {
        console.error('An error occurred:', err);
    }
}


generateModuleStatements();

oplist.forEach(op => {
    generateDocumentationPage(op);
})