/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */


const sidebars = {



  // By default, Docusaurus generates a sidebar from the docs folder structure
  learnSidebar: [
    { 
      type: 'category',
      label: 'Getting Started',
      link: {type:'doc', id: 'learn/getting-started/getting-started'},
      collapsed: false,
      collapsible: false,
      items: [
        'learn/getting-started/compare_versions',
        'learn/getting-started/dataflow',
        'learn/getting-started/weave',
        'learn/getting-started/interface',
      ],
    }, 
    {
      type: 'category',
      label: 'Examples', 
      collapsed: false,
      collapsible: false,
      items: [{  type: 'autogenerated', 
        dirName: 'learn/examples'}],
    }
    ],

  referenceSidebar:[
    {
      type: 'category',
      label: 'Core Concepts',
      collapsed: false, 
      collapsible: false,
      items:[
        'reference/glossary/parametric-design',
        'reference/glossary/operation',
        'reference/glossary/draft',
        'reference/glossary/dataflow',
        'reference/glossary/parameter'
      ]
    },
    { 
      type:'category',
      label: 'Operations (A-Z)',
      collapsed: true,
      collapsible: true,
      link: {type: 'doc', id: 'reference/operations/operations'},
      items:[ 
        'reference/operations/margin',
        'reference/operations/combos',
        'reference/operations/assign_systems',
        'reference/operations/bind_warp_floats',
        'reference/operations/bind_weft_floats',
        'reference/operations/chaos',
        'reference/operations/clear',
        'reference/operations/complextwill',
        'reference/operations/crop',
        'reference/operations/cutout',
        'reference/operations/deinterlace',
        'reference/operations/diff',
        "reference/operations/erase_blank_rows",
        "reference/operations/fill",
        "reference/operations/flip",
        'reference/operations/direct_loom',
        'reference/operations/floor_loom',
        'reference/operations/glitchsatin',
        'reference/operations/imagemap',
        'reference/operations/interlacewarps',
        'reference/operations/interlace',
        'reference/operations/invert',
        'reference/operations/join_left',
        'reference/operations/join_top',
        'reference/operations/layer',
        'reference/operations/notation',
        'reference/operations/directdrawdown',
        'reference/operations/drawdown',
        'reference/operations/makesymmetric',
        'reference/operations/mask',
        'reference/operations/overlay_multiple',
        'reference/operations/overlay',
        'reference/operations/weft_profile',
        'reference/operations/warp_profile',
        'reference/operations/random',
        'reference/operations/rectangle',
        'reference/operations/resize',
        'reference/operations/rotate',
        'reference/operations/sample_length',
        'reference/operations/sample_width',
        'reference/operations/satinish',
        'reference/operations/selvedge',
        'reference/operations/atop',
        'reference/operations/set_down_to_unset',
        'reference/operations/set_unset',
        'reference/operations/sine',
        'reference/operations/slope',
        'reference/operations/splice_in_warps',
        'reference/operations/splice_in_wefts',
        'reference/operations/stretch',
        'reference/operations/tabbyder',
        'reference/operations/tile',
        'reference/operations/twill',
        'reference/operations/undulatewarps',
        'reference/operations/undulatewefts',
        'reference/operations/bwimagemap',
        'reference/operations/waffle',
        'reference/operations/waffleish',
        'reference/operations/warp_profile',
        'reference/operations/weft_profile'
      ]
    },
    {
      type: 'category',
      label: 'Glossary',
      collapsed: true,
      collapsible: true,
      link: {type: 'doc', id:'reference/glossary/glossary'},
      items: [
        {type:'autogenerated',
        dirName:'reference/glossary'}
      ]
    }
  ]
  ,

  // operationsSidebar: [
  //  {
  //   type: 'category',
  //   label: 'operations',
  //   link: {type: 'doc', id: 'reference/operations/operations'},
  //   items:[ 
  //     'reference/operations/margin',
  //     'reference/operations/combos',
  //     'reference/operations/assign_systems',
  //     'reference/operations/bind_warp_floats',
  //     'reference/operations/bind_weft_floats',
  //     'reference/operations/chaos',
  //     'reference/operations/clear',
  //     'reference/operations/complextwill',
  //     'reference/operations/crop',
  //     'reference/operations/cutout',
  //     'reference/operations/deinterlace',
  //     'reference/operations/diff',
  //     "reference/operations/erase_blank_rows",
  //     "reference/operations/fill",
  //     "reference/operations/flip",
  //     'reference/operations/direct_loom',
  //     'reference/operations/floor_loom',
  //     'reference/operations/glitchsatin',
  //     'reference/operations/imagemap',
  //     'reference/operations/interlacewarps',
  //     'reference/operations/interlace',
  //     'reference/operations/invert',
  //     'reference/operations/join_left',
  //     'reference/operations/join_top',
  //     'reference/operations/layer',
  //     'reference/operations/notation',
  //     'reference/operations/directdrawdown',
  //     'reference/operations/drawdown',
  //     'reference/operations/makesymmetric',
  //     'reference/operations/mask',
  //     'reference/operations/overlay_multiple',
  //     'reference/operations/overlay',
  //     'reference/operations/weft_profile',
  //     'reference/operations/warp_profile',
  //     'reference/operations/random',
  //     'reference/operations/rectangle',
  //     'reference/operations/resize',
  //     'reference/operations/rotate',
  //     'reference/operations/sample_length',
  //     'reference/operations/sample_width',
  //     'reference/operations/satinish',
  //     'reference/operations/selvedge',
  //     'reference/operations/atop',
  //     'reference/operations/set_down_to_unset',
  //     'reference/operations/set_unset',
  //     'reference/operations/sine',
  //     'reference/operations/slope',
  //     'reference/operations/splice_in_warps',
  //     'reference/operations/splice_in_wefts',
  //     'reference/operations/stretch',
  //     'reference/operations/tabbyder',
  //     'reference/operations/tile',
  //     'reference/operations/twill',
  //     'reference/operations/undulatewarps',
  //     'reference/operations/undulatewefts',
  //     'reference/operations/bwimagemap',
  //     'reference/operations/waffle',
  //     'reference/operations/waffleish',
  //     'reference/operations/warp_profile',
  //     'reference/operations/weft_profile'
  //   ]
  //  },
  
  // ],

 
  devSidebar: [
    {type: 'autogenerated', 
      dirName: 'develop'}]
};

module.exports = sidebars;
