
const sidebars = {



  // By default, Docusaurus generates a sidebar from the docs folder structure
  aboutSidebar: [
    {
      type: 'doc',
      id: 'about/about', // document ID
      label: 'About', // sidebar label
    },
    {
      type: 'doc',
      id: 'about/research', // document ID
      label: 'Research', // sidebar label
    }
  ],
  contributeSidebar: [{
    type: 'doc',
    label: 'Contribute',
    id: 'contribute/contribute',
  },
  {
    type: 'doc',
    id: 'contribute/contributors',
    label: 'Contributors'
  },
  {
    type: 'doc',
    id: 'contribute/donate',
    label: 'Donate'
  }
  ],
  learnSidebar: [
    {
      type: 'html',
      value: 'Get Started',
      defaultStyle: true,
      className: 'sidebarHeading'
    },
    {
      type: 'doc',
      id: 'learn/getting-started/getting-started', // document ID
      label: 'How to AdaCAD', // sidebar label
    },
    {
      type: 'category',
      label: 'Key Concepts',
      collapsed: false,
      collapsible: false,
      link: { type: 'doc', id: 'learn/key-concepts/key-concepts' },
      items: [
        'reference/glossary/parametric-design',
        'reference/glossary/dataflow',
        'reference/glossary/seed-draft',
        'reference/glossary/operation',
        'reference/glossary/system',
        'reference/glossary/layer-notation'
      ],
    },
    {
      type: 'doc',
      id: 'learn/workshops-and-events', // document ID
      label: 'Workshops and Events', // sidebar label
    },
    {
      type: 'category',
      label: 'Tutorials',
      collapsed: true,
      collapsible: true,
      link: { type: 'doc', id: 'learn/tutorials/index' },
      items: [
        'learn/tutorials/figured_weaving_tc2',
        'learn/tutorials/block_threading',
        'learn/tutorials/multi-layer',
        'learn/tutorials/weave_tc2',
        'learn/tutorials/weave_avl'
      ],
    },
    {
      type: 'category',
      label: 'Our Projects',
      collapsed: true,
      collapsible: true,
      link: { type: 'doc', id: 'learn/examples/index' },
      items: [
        'learn/examples/lattice-tutorial',
        'learn/examples/hygromorphic-linen',
        'learn/examples/forcepocket',
      ],
    },

    {
      type: 'html',
      value: 'Reference',
      defaultStyle: true,
      className: 'sidebarHeading'
    },
    {
      type: 'category',
      label: 'Operations (A-Z)',
      collapsed: true,
      collapsible: true,
      link: { type: 'doc', id: 'reference/operations/index' },
      items: [
        {
          type: 'html',
          value: 'Structure',
          defaultStyle: true,
          className: 'subSidebarHeading'
        },
        {
          type: 'autogenerated',
          dirName: 'reference/operations/structure',
        },
        {
          type: 'html',
          value: 'Transformation',
          defaultStyle: true,
          className: 'subSidebarHeading'
        },
        {
          type: 'autogenerated',
          dirName: 'reference/operations/transformation',
        },
        {
          type: 'html',
          value: 'Cloth',
          defaultStyle: true,
          className: 'subSidebarHeading'
        },
        {
          type: 'autogenerated',
          dirName: 'reference/operations/cloth'
        },
        {
          type: 'html',
          value: 'Compound',
          defaultStyle: true,
          className: 'subSidebarHeading'
        },
        {
          type: 'autogenerated',
          dirName: 'reference/operations/compound'
        },
        {
          type: 'html',
          value: 'Dissect',
          defaultStyle: true,
          className: 'subSidebarHeading'
        },
        {
          type: 'autogenerated',
          dirName: 'reference/operations/dissect'
        },
        {
          type: 'html',
          value: 'Compute',
          defaultStyle: true,
          className: 'subSidebarHeading'
        },
        {
          type: 'autogenerated',
          dirName: 'reference/operations/compute'
        },
        {
          type: 'html',
          value: 'Helper',
          defaultStyle: true,
          className: 'subSidebarHeading'
        },
        {
          type: 'autogenerated',
          dirName: 'reference/operations/helper'
        },
        {
          type: 'html',
          value: 'Color Effect',
          defaultStyle: true,
          className: 'subSidebarHeading'
        },
        {
          type: 'autogenerated',
          dirName: 'reference/operations/color'
        },

        {
          type: 'html',
          value: 'Drafting Style',
          defaultStyle: true,
          className: 'subSidebarHeading'
        },
        {
          type: 'autogenerated',
          dirName: 'reference/operations/style'
        }

      ]
    },
    {
      type: 'category',
      label: 'Glossary',
      collapsed: true,
      collapsible: true,
      link: { type: 'doc', id: 'reference/glossary/index' },
      items: [

        {
          type: 'autogenerated',
          dirName: 'reference/glossary'
        }
      ]
    },
    {
      type: 'category',
      label: 'Interface',
      collapsed: true,
      collapsible: true,
      link: { type: 'doc', id: 'reference/interface/index' },
      items: [
        'reference/interface/topbar',
        'reference/interface/workspace',
        'reference/interface/draft_editor',
        'reference/interface/viewer'
      ]
    },


    // end reference sidebar
  ],


  devSidebar: [
    {
      type: 'autogenerated',
      dirName: 'develop'
    }]
};

module.exports = sidebars;
