/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */


const sidebars = {



  // By default, Docusaurus generates a sidebar from the docs folder structure
  learnSidebar: [
    {
      type: 'autogenerated', 
      dirName: 'learn'}],

  operationSidebar: [
   {
    type: 'category',
    label: 'Operations',
    link: {type: 'doc', id: 'operations/operations'},
    items:[ 
      'operations/margin',
      'operations/combos',
      'operations/assign_systems',
      'operations/bind_warp_floats',
      'operations/bind_weft_floats',
      'operations/chaos',
      'operations/clear',
      'operations/complextwill',
      'operations/crop',
      'operations/cutout',
      'operations/deinterlace',
      'operations/diff',
      "operations/erase_blank_rows",
      "operations/fill",
      "operations/flip",
      'operations/direct_loom',
      'operations/floor_loom',
      'operations/glitchsatin',
      'operations/imagemap',
      'operations/interlacewarps',
      'operations/interlace',
      'operations/invert',
      'operations/join_left',
      'operations/join_top',
      'operations/layer',
      'operations/notation',
      'operations/directdrawdown',
      'operations/drawdown',
      'operations/makesymmetric',
      'operations/mask',
      'operations/overlay_multiple',
      'operations/overlay',
      'operations/weft_profile',
      'operations/warp_profile',
      'operations/random',
      'operations/rectangle',
      'operations/resize',
      'operations/rotate',
      'operations/sample_length',
      'operations/sample_width',
      'operations/satinish',
      'operations/selvedge',
      'operations/atop',
      'operations/set_down_to_unset',
      'operations/set_unset',
      'operations/sine',
      'operations/slope',
      'operations/splice_in_warps',
      'operations/splice_in_wefts',
      'operations/stretch',
      'operations/tabbyder',
      'operations/tile',
      'operations/twill',
      'operations/undulatewarps',
      'operations/undulatewefts',
      'operations/bwimagemap',
      'operations/waffle',
      'operations/waffleish',
      'operations/warp_profile',
      'operations/weft_profile'
    ]
   },
  
  ],

 
  devSidebar: [
    {type: 'autogenerated', 
      dirName: 'develop'}]
};

module.exports = sidebars;
